### ISSUE TITLE
Automatically give new users permissions to create&modify hours/entry objects

### ISSUE THREAD

**Issue by tituomin** [City-of-Helsinki/helpt#8]
Rules:
POSTing an Entry is allowed for all users.
PUTting into an Entry is allowed for superusers and if entry.user == request.user

**Comment by tituomin** [comment]
http://www.django-rest-framework.org/api-guide/permissions/

**Comment by vikoivun** [comment]
Now as the simplest possible model, where everyone logged in can read&write
